version: "3.4"

services:
  api:
    build:
      context: ./server
    container_name: api
    networks:
      - app-net

  nginx:
    build: ./web
    container_name: nginx
    depends_on:
      - api
    ports:
      - 80:80
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
