version: "3.4"

services:
  db:
    image: postgres:15.1
    container_name: db
    environment:
      POSTGRES_DB: "app"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "qwe"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    networks:
      - app-net
    ports:
      - "5432:5432"

  api:
    build:
      context: ./server
    container_name: api
    depends_on:
      - db
    networks:
      - app-net

  nginx:
    build: ./web
    container_name: nginx
    depends_on:
      - api
    ports:
      - 80:80
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
